Repository HDD-kiosk/HDD, pull requests merged in 2022-04, with the labels that each got.

#3 Singsoong
  package-lock.json
  package.json
  src/components/CalTable.js
  src/components/ShoppingBasket.js
  src/img/shopping_cart.png
  src/views/Home/Home.js
Labels: feature 🎄

#5 feat: Main_Guest, Main_Guest_Modal, PayMent(결제) UI 구현
  src/img/cash.png
  src/img/comingsoon.png
  src/img/creditCard.png
  src/img/eventPromotion.png
  src/img/forhere.png
  src/img/hddLogo.png
  src/img/mic.png
  src/img/pay.png
  src/img/takeout.png
  src/views/Guest/Order/MainGuest.css
  src/views/Guest/Order/MainGuest.js
  src/views/Guest/Order/Modal.js
  src/views/Guest/Order/Payment.js
Labels: feature 🎄

#6 Hojin
  package-lock.json
  package.json
  src/App.js
  src/img/googlelogo.png
  src/img/hddlogo.png
  src/img/loopy.png
  src/index.js
  src/views/Guest/Order/Order.js
  src/views/Login/Login.js
Labels: feature 🎄

#13 feat: 회원가입 UI & Mode UI 구현
  src/App.js
  src/components/ShoppingBasket.js
  src/views/Mode/Mode.js
  src/views/Signup/Signup.js
Labels: feature 🎄

#11 refactor: Refactor MainGuest.js
  package-lock.json
  src/views/Guest/Order/MainGuest.js
Labels: refactor 🪐

#12 layout: font 적용
  public/index.html
  src/index.css
Labels: chore 💪
